version: '3'
services:
  app-dev:
    hostname: app
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    # volumes:
    #   - ./:/app/
      # - node_modules:/app/node_modules/

# volumes:
  # node_modules: