version: '3'
services:
  database:
    hostname: database
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 3

  # pgadmin:
  #   hostname: pgadmin
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   depends_on:
  #     - database
  #   ports:
  #     - '5555:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   restart: unless-stopped

  app-dev:
    hostname: app
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - '8081:8081'
      # - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - ./:/app/
      - node_modules_dev:/app/node_modules/

volumes:
  postgres_payment_data:
  # pgadmin_data:
  node_modules_dev: